version: "3.8"
services:
  mysqldb:
    container_name: "aldeamo-db"
    image: "mysql:5.7"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD

  app:
    depends_on:
      - mysqldb
    container_name: "aldeamo-app"
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url"  : "jdbc:mysql://mysqldb:$DATABASE_DOCKER_PORT/$DATABASE_NAME?autoReconnect=true&useSSL=false",
               "spring.datasource.username" : "$DATABASE_USERNAME",
               "spring.datasource.password" : "$DATABASE_PASSWORD",
               "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
               "spring.jpa.hibernate.ddl-auto" : "none"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


